// <auto-generated />
namespace BankService1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_transactions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_transactions));
        
        string IMigrationMetadata.Id
        {
            get { return "202202151620538_add_transactions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
