// <auto-generated />
namespace BankService1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_dateTime_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_dateTime_account));
        
        string IMigrationMetadata.Id
        {
            get { return "202201211934384_update_dateTime_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
